on:
  push:
    branches:
    - fx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get Github tag
        id: meta
        run: |
          echo "tag=$(git describe --always --tags --match='v*' | sed -e 's/^v//')" >> "$GITHUB_OUTPUT"

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            functionx/zkevm-bridge-service
            functionx/zkevm-bridge-service:${{ steps.meta.outputs.tag }}
          build-args: |
            PRIVATE_TOKEN=${{secrets.GIT_TOKEN}}
